name: Jekyll site CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download AWS CLI & Jekyll
      run: |
        sudo apt update && \
        sudo apt install awscli jekyll

    - name: Run Makefile
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets. aws_access_key_id }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets. aws_secret_access_key }}
      run: |
        make publish
